### ISSUE TITLE
CSS won't load in views

### ISSUE THREAD

**Issue by fardin01** [Freeways/messenger-bot-sails#3]
Hi,

CSS files won't load in my views. I narrowed it down to a grunt issue
(https://stackoverflow.com/questions/36715961/sailsjs-tmp-folder-not-updated-or-created-automatically)

But can't work out how to fix it. I'd appreciate some help!

**Comment by bashz** [comment]
Hello sorry for the delay, actually grunt was deactivated because the main purpose was building a chatbot, I am reactivating it right now since I see no harm to have it up :wink:

**Comment by bashz** [comment]
@fardin01 this should work fine now, please do not hesitate to report any thing that breaks in your end or something that bothers you

Meanwhile I will also update the readme so those who don't need grunt can deactivate it
